/* ══════════════════════════════════════════════════════════
   glossary.js — Pearl-poet lexicon
   Covers all pre-loaded passages + core Cotton Nero A.x
   vocabulary. Source: Middle English Dictionary (MED),
   Andrew & Waldron 5th ed., Gordon's Pearl edition.
   Keys are lowercase Middle English spellings.
   ══════════════════════════════════════════════════════════ */

const GLOSSARY = {
  /* ── Articles, pronouns, prepositions, conjunctions ─────── */
  "þe":       { modern: "the",           phonetic: "thuh",       grammar: "def.art." },
  "þat":      { modern: "that",          phonetic: "that",       grammar: "dem.pron./conj." },
  "þis":      { modern: "this",          phonetic: "this",       grammar: "dem.pron." },
  "þer":      { modern: "there / where", phonetic: "thair",      grammar: "adv." },
  "þerof":    { modern: "thereof",       phonetic: "thair-OV",   grammar: "adv." },
  "þurȝ":     { modern: "through",       phonetic: "thurgh",     grammar: "prep." },
  "þou":      { modern: "thou / you",    phonetic: "thoo",       grammar: "pron.2sg.nom." },
  "þe":       { modern: "thee",          phonetic: "thee",       grammar: "pron.2sg.acc." },
  "þay":      { modern: "they",          phonetic: "thay",       grammar: "pron.3pl.nom." },
  "hem":      { modern: "them",          phonetic: "hem",        grammar: "pron.3pl.acc." },
  "hyr":      { modern: "her / it",      phonetic: "heer",       grammar: "pron.3sg.acc.f." },
  "hit":      { modern: "it",            phonetic: "hit",        grammar: "pron.3sg.neut." },
  "hym":      { modern: "him",           phonetic: "him",        grammar: "pron.3sg.acc.m." },
  "his":      { modern: "his",           phonetic: "his",        grammar: "pron.3sg.gen.m." },
  "ho":       { modern: "she",           phonetic: "hoh",        grammar: "pron.3sg.nom.f." },
  "her":      { modern: "their",         phonetic: "hair",       grammar: "pron.3pl.gen." },
  "al":       { modern: "all",           phonetic: "al",         grammar: "adj./pron." },
  "alle":     { modern: "all",           phonetic: "AL-luh",     grammar: "adj./pron." },
  "of":       { modern: "of",            phonetic: "ov",         grammar: "prep." },
  "in":       { modern: "in",            phonetic: "in",         grammar: "prep." },
  "to":       { modern: "to",            phonetic: "toh",        grammar: "prep./inf.particle" },
  "at":       { modern: "at",            phonetic: "at",         grammar: "prep." },
  "as":       { modern: "as",            phonetic: "az",         grammar: "conj./adv." },
  "so":       { modern: "so",            phonetic: "soh",        grammar: "adv./conj." },
  "bot":      { modern: "but",           phonetic: "bot",        grammar: "conj." },
  "and":      { modern: "and",           phonetic: "and",        grammar: "conj." },
  "ne":       { modern: "nor / not",     phonetic: "nuh",        grammar: "neg.conj." },
  "on":       { modern: "on / in",       phonetic: "on",         grammar: "prep." },
  "wyth":     { modern: "with",          phonetic: "with",       grammar: "prep." },
  "fro":      { modern: "from",          phonetic: "froh",       grammar: "prep." },
  "for":      { modern: "for",           phonetic: "for",        grammar: "prep./conj." },
  "bi":       { modern: "by",            phonetic: "bee",        grammar: "prep." },
  "by":       { modern: "by",            phonetic: "bee",        grammar: "prep." },
  "vp":       { modern: "up",            phonetic: "up",         grammar: "adv./prep." },
  "oute":     { modern: "out",           phonetic: "oot",        grammar: "adv./prep." },
  "doun":     { modern: "down",          phonetic: "doon",       grammar: "adv./prep." },
  "vpon":     { modern: "upon",          phonetic: "up-ON",      grammar: "prep." },
  "þen":      { modern: "then",          phonetic: "then",       grammar: "adv./conj." },
  "er":       { modern: "ere / before",  phonetic: "air",        grammar: "conj./prep." },
  "quere":    { modern: "where",         phonetic: "KWAIR-uh",   grammar: "adv." },
  "how":      { modern: "how",           phonetic: "hoo",        grammar: "adv." },
  "when":     { modern: "when",          phonetic: "hwen",       grammar: "conj./adv." },

  /* ── Common verbs ────────────────────────────────────────── */
  "watz":     { modern: "was",           phonetic: "watz",       grammar: "v.past.3sg." },
  "is":       { modern: "is",            phonetic: "iz",         grammar: "v.pres.3sg." },
  "arn":      { modern: "are",           phonetic: "arn",        grammar: "v.pres.3pl." },
  "haf":      { modern: "have",          phonetic: "hav",        grammar: "v.pres.1sg." },
  "hatz":     { modern: "has",           phonetic: "hatz",       grammar: "v.pres.3sg." },
  "may":      { modern: "may",           phonetic: "may",        grammar: "v.modal.pres." },
  "myȝt":     { modern: "might",         phonetic: "myght",      grammar: "v.modal.past." },
  "schal":    { modern: "shall",         phonetic: "shal",       grammar: "v.modal.pres." },
  "wolde":    { modern: "would",         phonetic: "WOL-duh",    grammar: "v.modal.past." },
  "cowþe":    { modern: "could / knew how to", phonetic: "kooth", grammar: "v.modal.past." },
  "saye":     { modern: "say",           phonetic: "SAY-uh",     grammar: "v.inf." },
  "sette":    { modern: "set / placed",  phonetic: "SET-tuh",    grammar: "v.past.1sg." },
  "proved":   { modern: "proved / tested", phonetic: "PROV-ed",  grammar: "v.past.1sg." },
  "jugged":   { modern: "judged / assessed", phonetic: "JUG-ged", grammar: "v.past.1sg." },
  "syȝ":      { modern: "saw",           phonetic: "seedge",     grammar: "v.past.3sg." },
  "syȝe":     { modern: "saw",           phonetic: "SEE-yuh",    grammar: "v.past.1sg." },
  "stod":     { modern: "stood",         phonetic: "stod",       grammar: "v.past.3sg." },
  "stared":   { modern: "stared",        phonetic: "STAIR-ed",   grammar: "v.past.3sg." },
  "fonde":    { modern: "found",         phonetic: "FON-duh",    grammar: "v.past.3sg." },
  "rynnez":   { modern: "runs",          phonetic: "RIN-ez",     grammar: "v.pres.3sg." },
  "fest":     { modern: "fasted / held", phonetic: "fest",       grammar: "v.past.3sg." },
  "slydes":   { modern: "slides",        phonetic: "SLEED-ez",   grammar: "v.pres.3sg." },
  "blunt":    { modern: "came / struck", phonetic: "blunt",      grammar: "v.past.3sg." },
  "festnes":  { modern: "fastens",       phonetic: "FES-tnez",   grammar: "v.pres.3sg." },
  "suffer":   { modern: "suffer / endure", phonetic: "SUF-fer",  grammar: "v.inf." },
  "calle":    { modern: "call",          phonetic: "KAL-luh",    grammar: "v.inf." },
  "comaunded":{ modern: "commanded",    phonetic: "koh-MAN-ded", grammar: "v.past.3sg." },
  "reden":    { modern: "read / counsel", phonetic: "REE-den",   grammar: "v.pl.pres." },
  "syngen":   { modern: "sing",          phonetic: "SING-en",    grammar: "v.pl.pres." },
  "aprochen": { modern: "approach",      phonetic: "ah-PRO-chen", grammar: "v.pl.pres." },
  "rede":     { modern: "read / interpret", phonetic: "REE-duh", grammar: "v.imp." },
  "comende":  { modern: "commend / praise", phonetic: "koh-MEN-duh", grammar: "v.inf." },
  "rekken":   { modern: "recount / enumerate", phonetic: "REK-ken", grammar: "v.inf." },
  "carpe":    { modern: "speak / talk",  phonetic: "KAR-puh",    grammar: "v.inf." },
  "drof":     { modern: "drove / pushed", phonetic: "drof",      grammar: "v.past.3sg." },
  "wroȝt":    { modern: "wrought / made", phonetic: "wroght",    grammar: "v.past.3sg." },
  "tried":    { modern: "tried / convicted", phonetic: "TREE-ed", grammar: "v.past.3sg." },
  "depreced": { modern: "subdued / conquered", phonetic: "deh-PREST", grammar: "v.past.3sg." },
  "bicome":   { modern: "became",        phonetic: "bih-KOM",    grammar: "v.past.3pl." },
  "brittened":{ modern: "shattered / destroyed", phonetic: "BRIT-tend", grammar: "v.past.3sg." },
  "sesed":    { modern: "ceased",        phonetic: "SEE-zed",    grammar: "v.past.3sg." },
  "hales":    { modern: "comes / enters hastily", phonetic: "HAY-lez", grammar: "v.pres.3sg." },
  "folȝez":   { modern: "follows",       phonetic: "FOL-yez",    grammar: "v.pres.3sg." },
  "leste":    { modern: "lost",          phonetic: "LES-tuh",    grammar: "v.past.1sg." },
  "dewyne":   { modern: "pine / wither", phonetic: "deh-WINE",   grammar: "v.pres.1sg." },
  "wayted":   { modern: "watched / waited", phonetic: "WAY-ted",  grammar: "v.past.1sg." },
  "sprange":  { modern: "sprang / flew", phonetic: "spran-yuh",  grammar: "v.past.3sg." },
  "yot":      { modern: "went / fell",   phonetic: "yot",        grammar: "v.past.3sg." },
  "telle":    { modern: "tell",          phonetic: "TEL-luh",    grammar: "v.inf." },
  "maches":   { modern: "makes terms / contracts", phonetic: "MA-chez", grammar: "v.pres.3sg." },
  "makes":    { modern: "makes / pays",  phonetic: "MAY-kez",    grammar: "v.pres.3sg." },
  "lakked":   { modern: "lacked",        phonetic: "LAK-ed",     grammar: "v.past.3sg." },
  "loked":    { modern: "looked / belonged", phonetic: "LOK-ed",  grammar: "v.past.3sg." },
  "expowne":  { modern: "expound / explain", phonetic: "ex-POWN-uh", grammar: "v.imp." },
  "gyf":      { modern: "give",          phonetic: "yiv",        grammar: "v.pres.1sg." },
  "passe":    { modern: "surpass",       phonetic: "PAS-suh",    grammar: "v.inf." },
  "gryþe":    { modern: "receive / honour", phonetic: "greeth",  grammar: "v.pres.1sg." },

  /* ── Pearl poem key vocabulary ───────────────────────────── */
  "perle":    { modern: "pearl",         phonetic: "PER-luh",    grammar: "n.nom.sg." },
  "plesaunte":{ modern: "pleasing",      phonetic: "pleh-ZON-tuh", grammar: "adj." },
  "prynces":  { modern: "prince's",      phonetic: "PRIN-sez",   grammar: "n.gen.sg." },
  "paye":     { modern: "pleasure / satisfaction", phonetic: "PAY-uh", grammar: "n." },
  "clanly":   { modern: "cleanly / purely", phonetic: "KLAN-lee", grammar: "adv." },
  "clos":     { modern: "enclose / set (in a setting)", phonetic: "klohz", grammar: "v.inf." },
  "golde":    { modern: "gold",          phonetic: "GOL-duh",    grammar: "n." },
  "clere":    { modern: "bright / clear", phonetic: "KLAIR",     grammar: "adj." },
  "oryent":   { modern: "the Orient / the East", phonetic: "OR-ee-ent", grammar: "n." },
  "hardyly":  { modern: "boldly / certainly", phonetic: "HAR-dee-lee", grammar: "adv." },
  "precios":  { modern: "precious",      phonetic: "PRET-si-os", grammar: "adj." },
  "pere":     { modern: "peer / equal",  phonetic: "pair",       grammar: "n." },
  "rounde":   { modern: "round",         phonetic: "ROON-duh",   grammar: "adj." },
  "reken":    { modern: "fair / beautiful / precious", phonetic: "REK-en", grammar: "adj." },
  "uche":     { modern: "each",          phonetic: "OO-chuh",    grammar: "adj." },
  "araye":    { modern: "array / setting / arrangement", phonetic: "ah-RAY-uh", grammar: "n." },
  "smal":     { modern: "slender / fine / small", phonetic: "smal", grammar: "adj." },
  "smoþe":    { modern: "smooth",        phonetic: "SMOTH-uh",   grammar: "adj." },
  "sydez":    { modern: "sides",         phonetic: "SEE-dez",    grammar: "n.pl." },
  "gemmes":   { modern: "gems",          phonetic: "GEM-mez",    grammar: "n.pl." },
  "gaye":     { modern: "gay / bright / splendid", phonetic: "GAY-uh", grammar: "adj." },
  "sengeley": { modern: "uniquely / singly", phonetic: "SEN-yuh-lee", grammar: "adv." },
  "synglere": { modern: "without equal / singular", phonetic: "SIN-gluh-ruh", grammar: "adj./n." },
  "allas":    { modern: "alas",          phonetic: "ah-LAS",     grammar: "interj." },
  "erbere":   { modern: "herb garden / arbour", phonetic: "ER-buh-ruh", grammar: "n." },
  "gresse":   { modern: "grass",         phonetic: "GRES-suh",   grammar: "n." },
  "grounde":  { modern: "ground",        phonetic: "GROON-duh",  grammar: "n." },
  "fordolked":{ modern: "wounded / pierced with grief", phonetic: "for-DOL-ked", grammar: "v.pp." },
  "luf-daungere": { modern: "love's power / danger of love", phonetic: "luf-DAWN-yuh-ruh", grammar: "n." },
  "pryvy":    { modern: "precious / private / hidden", phonetic: "PRIV-ee", grammar: "adj." },
  "wythouten":{ modern: "without",       phonetic: "with-OO-ten", grammar: "prep." },
  "spot":     { modern: "spot / blemish / place", phonetic: "spot", grammar: "n." },
  "spote":    { modern: "spot / place",  phonetic: "SPOT-uh",    grammar: "n." },
  "syþen":    { modern: "since / afterwards", phonetic: "SEE-then", grammar: "adv./conj." },
  "siþen":    { modern: "since / afterwards", phonetic: "SEE-then", grammar: "adv./conj." },
  "wele":     { modern: "well-being / joy / wealth", phonetic: "WEH-luh", grammar: "n." },
  "wont":     { modern: "was accustomed / wont", phonetic: "wont", grammar: "adj./v.past." },
  "whyle":    { modern: "while / at one time", phonetic: "HWEE-luh", grammar: "conj./n." },
  "devoyde":  { modern: "remove / drive away", phonetic: "deh-VOI-duh", grammar: "v.inf." },
  "wrange":   { modern: "wrong / sorrow", phonetic: "WRAN-yuh",  grammar: "n." },
  "heven":    { modern: "lift / raise",  phonetic: "HEV-en",     grammar: "v.inf." },
  "happe":    { modern: "happiness / fortune", phonetic: "HAP-puh", grammar: "n." },
  "hele":     { modern: "health / salvation / well-being", phonetic: "HEH-luh", grammar: "n." },
  "wyschande":{ modern: "wishing / desiring", phonetic: "WISH-an-duh", grammar: "v.pres.p." },
  "apostel":  { modern: "apostle",       phonetic: "ah-POS-tel",  grammar: "n." },
  "syȝt":     { modern: "sight / vision", phonetic: "seedgt",    grammar: "n." },
  "cyty":     { modern: "city",          phonetic: "SIT-ee",     grammar: "n." },
  "gret":     { modern: "great",         phonetic: "gret",       grammar: "adj." },
  "renoun":   { modern: "renown / fame", phonetic: "reh-NOON",   grammar: "n." },
  "nwe":      { modern: "new",           phonetic: "nyoo",       grammar: "adj." },
  "ryally":   { modern: "royally",       phonetic: "ree-AL-ee",  grammar: "adv." },
  "dyȝt":     { modern: "adorned / arrayed / prepared", phonetic: "dyght", grammar: "v.pp." },
  "lyȝt":     { modern: "light / descended", phonetic: "lyght",  grammar: "n./v.past." },
  "borȝ":     { modern: "city / borough", phonetic: "borgh",     grammar: "n." },
  "brende":   { modern: "burnished / pure", phonetic: "BREN-duh", grammar: "adj." },
  "bryȝt":    { modern: "bright",        phonetic: "bryght",     grammar: "adj." },
  "glemande": { modern: "gleaming",      phonetic: "GLEM-an-duh", grammar: "v.pres.p." },
  "glas":     { modern: "glass",         phonetic: "glas",       grammar: "n." },
  "burnist":  { modern: "burnished",     phonetic: "BUR-nist",   grammar: "v.pp./adj." },
  "broun":    { modern: "bright / gleaming (not dark)", phonetic: "broon", grammar: "adj." },
  "gentyl":   { modern: "noble / gentle", phonetic: "GEN-til",   grammar: "adj." },
  "gemmez":   { modern: "gems",          phonetic: "GEM-mez",    grammar: "n.pl." },
  "anunder":  { modern: "beneath / set below", phonetic: "ah-NUN-der", grammar: "prep." },
  "pyȝt":     { modern: "set / fixed / adorned", phonetic: "pyght", grammar: "v.pp." },
  "bantlez":  { modern: "terraces / steps", phonetic: "BAN-tlez", grammar: "n.pl." },
  "twelve":   { modern: "twelve",        phonetic: "TWEL-vuh",   grammar: "num." },
  "basyng":   { modern: "base / foundation", phonetic: "BAY-sing", grammar: "n." },
  "boun":     { modern: "ready / set",   phonetic: "boon",       grammar: "adj." },

  /* ── Sir Gawain key vocabulary ───────────────────────────── */
  "sege":     { modern: "siege",         phonetic: "SEE-yuh",    grammar: "n." },
  "assaut":   { modern: "assault",       phonetic: "ah-SAWT",    grammar: "n." },
  "brent":    { modern: "burned",        phonetic: "brent",      grammar: "v.pp." },
  "brondez":  { modern: "brands / embers / torches", phonetic: "BRON-dez", grammar: "n.pl." },
  "askez":    { modern: "ashes",         phonetic: "AS-kez",     grammar: "n.pl." },
  "tulk":     { modern: "man / warrior", phonetic: "tulk",       grammar: "n." },
  "trammes":  { modern: "plots / schemes / treacheries", phonetic: "TRAM-mez", grammar: "n.pl." },
  "tresoun":  { modern: "treason",       phonetic: "TREZ-oon",   grammar: "n." },
  "tricherie":{ modern: "treachery",     phonetic: "TRICH-uh-ree", grammar: "n." },
  "trewest":  { modern: "most true / most loyal", phonetic: "TREW-est", grammar: "adj.superl." },
  "erþe":     { modern: "earth",         phonetic: "ER-thuh",    grammar: "n." },
  "athel":    { modern: "noble",         phonetic: "ATH-el",     grammar: "adj." },
  "highe":    { modern: "high / noble",  phonetic: "HEE-yuh",    grammar: "adj." },
  "kynde":    { modern: "race / family / nature", phonetic: "KIN-duh", grammar: "n." },
  "prouinces":{ modern: "provinces",     phonetic: "PROV-in-sez", grammar: "n.pl." },
  "patrounes":{ modern: "patrons / lords", phonetic: "PAT-roo-nez", grammar: "n.pl." },
  "welneȝe":  { modern: "well-nigh / nearly", phonetic: "wel-NEYGH", grammar: "adv." },
  "west":     { modern: "west",          phonetic: "west",       grammar: "adj./n." },
  "iles":     { modern: "isles",         phonetic: "EE-lez",     grammar: "n.pl." },
  "halle":    { modern: "hall",          phonetic: "HAL-luh",    grammar: "n." },
  "dor":      { modern: "door",          phonetic: "dor",        grammar: "n." },
  "aghlich":  { modern: "awe-inspiring / terrible", phonetic: "AGH-lich", grammar: "adj." },
  "mayster":  { modern: "master",        phonetic: "MAY-ster",   grammar: "n." },
  "molde":    { modern: "earth / ground / world", phonetic: "MOL-duh", grammar: "n." },
  "mesure":   { modern: "measure / size", phonetic: "meh-ZUR-uh", grammar: "n." },
  "hyghe":    { modern: "high / tall",   phonetic: "HEE-yuh",    grammar: "adj." },
  "swyre":    { modern: "neck",          phonetic: "SWEER-uh",   grammar: "n." },
  "þwange":   { modern: "thong / waist", phonetic: "THWAN-yuh",  grammar: "n." },
  "sware":    { modern: "square / stout", phonetic: "SWAIR",     grammar: "adj." },
  "þik":      { modern: "thick / stout", phonetic: "thik",       grammar: "adj." },
  "lyndes":   { modern: "loins / haunches", phonetic: "LIN-dez", grammar: "n.pl." },
  "lymes":    { modern: "limbs",         phonetic: "LEEM-ez",    grammar: "n.pl." },
  "longe":    { modern: "long",          phonetic: "LON-yuh",    grammar: "adj." },
  "grete":    { modern: "great / big",   phonetic: "GRET-uh",    grammar: "adj." },
  "etayn":    { modern: "giant",         phonetic: "EH-tayn",    grammar: "n." },
  "erde":     { modern: "earth / land",  phonetic: "ER-duh",     grammar: "n." },
  "hope":     { modern: "think / believe / suppose", phonetic: "HOP-uh", grammar: "v.pres.1sg." },
  "algate":   { modern: "at any rate / in every way", phonetic: "AL-gayt", grammar: "adv." },
  "mynn":     { modern: "deem / consider", phonetic: "min",      grammar: "v.inf." },
  "myriest":  { modern: "greatest / most mighty", phonetic: "MIR-ee-est", grammar: "adj.superl." },
  "muckel":   { modern: "great size / bulk", phonetic: "MUK-el", grammar: "n./adj." },
  "bak":      { modern: "back",          phonetic: "bak",        grammar: "n." },
  "brest":    { modern: "breast / chest", phonetic: "brest",     grammar: "n." },
  "bodi":     { modern: "body",          phonetic: "BOD-ee",     grammar: "n." },
  "sturne":   { modern: "stern / strong / fierce", phonetic: "STUR-nuh", grammar: "adj." },
  "wombe":    { modern: "belly / womb",  phonetic: "WOM-buh",    grammar: "n." },
  "wast":     { modern: "waist",         phonetic: "wayst",      grammar: "n." },
  "worthily": { modern: "fittingly / properly", phonetic: "WOR-thuh-lee", grammar: "adv." },
  "smale":    { modern: "slender / small", phonetic: "SMAL-uh",  grammar: "adj." },
  "þenk":     { modern: "think / consider", phonetic: "thenk",   grammar: "v.imp." },
  "wel":      { modern: "well",          phonetic: "wel",        grammar: "adv." },
  "woþe":     { modern: "peril / danger / harm", phonetic: "WOH-thuh", grammar: "n." },
  "wonde":    { modern: "flinch / hesitate", phonetic: "WON-duh", grammar: "v.subj." },
  "aventure": { modern: "adventure / challenge", phonetic: "ah-VEN-tuh-ruh", grammar: "n." },
  "frayn":    { modern: "enquire / pursue / take on", phonetic: "frayn", grammar: "v.inf." },
  "tan":      { modern: "taken",         phonetic: "tan",        grammar: "v.pp." },
  "honde":    { modern: "hand",          phonetic: "HON-duh",    grammar: "n." },

  /* ── Patience key vocabulary ─────────────────────────────── */
  "jonas":    { modern: "Jonah",         phonetic: "YOH-nas",    grammar: "prop.n." },
  "port":     { modern: "port / harbour", phonetic: "port",      grammar: "n." },
  "tarce":    { modern: "Tarshish",      phonetic: "TAR-suh",    grammar: "prop.n." },
  "prestly":  { modern: "promptly / quickly", phonetic: "PRES-tlee", grammar: "adv." },
  "fayr":     { modern: "fair / fine",   phonetic: "fayr",       grammar: "adj." },
  "schyp":    { modern: "ship",          phonetic: "shyp",       grammar: "n." },
  "fare":     { modern: "voyage / journey", phonetic: "FAR-uh",  grammar: "n." },
  "redy":     { modern: "ready",         phonetic: "REH-dee",    grammar: "adj." },
  "maryneres":{ modern: "mariners / sailors", phonetic: "mah-rin-ER-ez", grammar: "n.pl." },
  "tow":      { modern: "take / convey", phonetic: "toh",        grammar: "v.inf." },
  "tyd":      { modern: "quickly / in time", phonetic: "teed",   grammar: "adv." },
  "lore":     { modern: "learning / knowledge", phonetic: "LOR-uh", grammar: "n." },
  "stede":    { modern: "place / stead", phonetic: "STED-uh",    grammar: "n." },
  "wayke":    { modern: "weak",          phonetic: "WAY-kuh",    grammar: "adj." },
  "wynd":     { modern: "wind",          phonetic: "wind",       grammar: "n." },
  "walowande":{ modern: "rolling / weltering", phonetic: "WAL-oh-an-duh", grammar: "v.pres.p." },
  "wendes":   { modern: "waves",         phonetic: "WEN-dez",    grammar: "n.pl." },
  "dep":      { modern: "deep",          phonetic: "dep",        grammar: "adj./n." },
  "see":      { modern: "sea",           phonetic: "see",        grammar: "n." },
  "drowpen":  { modern: "be drowned / sink", phonetic: "DROO-pen", grammar: "v.inf." },
  "drenche":  { modern: "drown",         phonetic: "DREN-chuh",  grammar: "v.inf." },
  "flot":     { modern: "floated / flooring", phonetic: "flot",  grammar: "v.past.3sg./n." },
  "fayled":   { modern: "failed / was lacking", phonetic: "FAY-led", grammar: "v.past.3sg." },
  "noȝt":     { modern: "not / naught",  phonetic: "noght",      grammar: "adv./n." },
  "byst":     { modern: "beast",         phonetic: "byst",       grammar: "n." },
  "bely":     { modern: "belly",         phonetic: "BEL-ee",     grammar: "n." },
  "bore":     { modern: "bore / carried", phonetic: "BOR-uh",    grammar: "v.past.3sg." },
  "slopes":   { modern: "slopes / gullet", phonetic: "SLOP-ez",  grammar: "n.pl." },
  "syde":     { modern: "side",          phonetic: "SEED-uh",    grammar: "n." },
  "blok":     { modern: "block / chamber", phonetic: "blok",     grammar: "n." },
  "brod":     { modern: "broad / wide",  phonetic: "brod",       grammar: "adj." },
  "fete":     { modern: "feet",          phonetic: "FEH-tuh",    grammar: "n.pl." },
  "fathmez":  { modern: "gropes / reaches about", phonetic: "FATH-mez", grammar: "v.pres.3sg." },
  "stomak":   { modern: "stomach",       phonetic: "STO-mak",    grammar: "n." },
  "stank":    { modern: "stank",         phonetic: "stank",      grammar: "v.past.3sg." },
  "devel":    { modern: "devil",         phonetic: "DEV-el",     grammar: "n." },
  "saym":     { modern: "grease / lard / filth", phonetic: "saym", grammar: "n." },
  "sorȝe":    { modern: "sorrow / filth", phonetic: "SOR-yuh",   grammar: "n." },
  "savoured": { modern: "smelled / tasted of", phonetic: "SAH-verd", grammar: "v.past.3sg." },
  "helle":    { modern: "hell",          phonetic: "HEL-luh",    grammar: "n." },
  "bylded":   { modern: "built / established", phonetic: "BIL-ded", grammar: "v.past.3sg." },
  "bour":     { modern: "chamber / bower", phonetic: "boor",     grammar: "n." },
  "bale":     { modern: "evil / misery / harm", phonetic: "BAL-uh", grammar: "n." },

  /* ── Cleanness key vocabulary ────────────────────────────── */
  "clannesse":{ modern: "cleanliness / purity", phonetic: "KLAN-nes-uh", grammar: "n." },
  "who-so":   { modern: "whoever",       phonetic: "HOO-soh",    grammar: "pron." },
  "kyndly":   { modern: "fittingly / naturally", phonetic: "KIND-lee", grammar: "adv." },
  "resounz":  { modern: "reasons / grounds", phonetic: "REH-zoonz", grammar: "n.pl." },
  "ryȝt":     { modern: "right / justice", phonetic: "ryght",    grammar: "n./adj." },
  "fayre":    { modern: "fair / fitting", phonetic: "FAYR-uh",   grammar: "adj." },
  "formez":   { modern: "forms / examples", phonetic: "FOR-mez", grammar: "n.pl." },
  "forþering":{ modern: "furthering / advancing", phonetic: "FOR-ther-ing", grammar: "v.n." },
  "speche":   { modern: "speech",        phonetic: "SPECH-uh",   grammar: "n." },
  "contraré": { modern: "contrary / opposite", phonetic: "KON-truh-ray", grammar: "n./adj." },
  "comfort":  { modern: "comfort / strengthen", phonetic: "KOM-fort", grammar: "n./v.inf." },
  "perchance":{ modern: "perchance / perhaps", phonetic: "per-CHANS", grammar: "adv." },
  "wonder":   { modern: "wondrously / very", phonetic: "WON-der", grammar: "adv." },
  "wroth":    { modern: "wrathful / angry", phonetic: "wroath",  grammar: "adj." },
  "wyȝ":      { modern: "being / person (here: God)", phonetic: "wygh", grammar: "n." },
  "þynges":   { modern: "things",        phonetic: "THING-ez",   grammar: "n.pl." },
  "freke":    { modern: "man / fellow",  phonetic: "FREK-uh",    grammar: "n." },
  "fylþe":    { modern: "filth / impurity", phonetic: "FILTH-uh", grammar: "n." },
  "renkes":   { modern: "men / warriors", phonetic: "REN-kez",   grammar: "n.pl." },
  "relygioun":{ modern: "religious life / clergy", phonetic: "reh-LI-yoon", grammar: "n." },
  "presens":  { modern: "presence",      phonetic: "PRES-enz",   grammar: "n." },
  "prestes":  { modern: "priests",       phonetic: "PRES-tez",   grammar: "n.pl." },
  "kyng":     { modern: "king",          phonetic: "king",       grammar: "n." },
  "anoon":    { modern: "at once / immediately", phonetic: "ah-NOON", grammar: "adv." },
  "heþe":     { modern: "heathen / pagan", phonetic: "HEH-thuh", grammar: "adj." },
  "astrologes":{ modern: "astrologers",  phonetic: "as-TROL-oh-ges", grammar: "n.pl." },
  "sages":    { modern: "sages / wise men", phonetic: "SAH-yez", grammar: "n.pl." },
  "scole":    { modern: "school / learned", phonetic: "SKOL-uh", grammar: "n./adj." },
  "maystersȝ":{ modern: "masters",       phonetic: "MAY-ster-z", grammar: "n.pl." },
  "warlawes": { modern: "warlocks / magicians", phonetic: "WAR-loh-ez", grammar: "n.pl." },
  "wycchecraftes": { modern: "witchcrafts / sorceries", phonetic: "WICH-uh-kraf-tez", grammar: "n.pl." },
  "warlokez": { modern: "warlocks",      phonetic: "WAR-lok-ez", grammar: "n.pl." },
  "writyng":  { modern: "writing",       phonetic: "WREE-ting",  grammar: "n." },
  "worde":    { modern: "word",          phonetic: "WOR-duh",    grammar: "n." },
  "menyng":   { modern: "meaning",       phonetic: "MEN-ing",    grammar: "n." },
  "herberȝ":  { modern: "lodging / hall", phonetic: "HER-bergh", grammar: "n." },
  "clatour":  { modern: "cloth of gold / rich fabric", phonetic: "KLAH-toor", grammar: "n." },
  "coler":    { modern: "collar (of gold)", phonetic: "KOH-ler", grammar: "n." },
  "gyfte":    { modern: "gift",          phonetic: "YIFT-uh",    grammar: "n." },
  "nobly":    { modern: "nobly",         phonetic: "NOH-blee",   grammar: "adv." },
  "þrydde":   { modern: "third",         phonetic: "THRID-duh",  grammar: "num.ord." },
  "clad":     { modern: "clad / clothed", phonetic: "klad",      grammar: "v.pp." },
};

/* ══════════════════════════════════════════════════════════
   LOOKUP — normalise input and find best match
   ══════════════════════════════════════════════════════════ */
function lookupWord(raw) {
  const word = raw.toLowerCase().trim();

  // 1. Direct match
  if (GLOSSARY[word]) return { ...GLOSSARY[word], matched: word };

  // 2. Strip common endings and retry
  const stems = [
    word.replace(/ez$/, ''),     // plural -ez
    word.replace(/ez$/, 'e'),
    word.replace(/ez$/, 'es'),
    word.replace(/z$/, ''),      // -z plural
    word.replace(/ed$/, ''),     // past -ed
    word.replace(/ed$/, 'e'),
    word.replace(/ande$/, ''),   // pres. participle -ande
    word.replace(/ande$/, 'e'),
    word.replace(/ynde$/, ''),
    word.replace(/e$/, ''),      // final -e
    word.replace(/ly$/, ''),     // adverb -ly
    word.replace(/ly$/, 'le'),
  ];

  for (const stem of stems) {
    if (stem && GLOSSARY[stem]) return { ...GLOSSARY[stem], matched: stem };
  }

  // 3. Replace thorn/yogh variants and retry
  const normalized = word
    .replace(/þ/g, 'th')
    .replace(/ȝ/g, 'gh');
  if (GLOSSARY[normalized]) return { ...GLOSSARY[normalized], matched: normalized };

  return null;
}
